name: publish

on:
  push:
    branches: ['main']

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest

    steps:
      - name: checkout Repository
        uses: actions/checkout@v3
      - name: lowercase github.repository
        run: |
          echo "IMAGE_NAME=`echo ${{github.repository}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}
      - name: determine version
        run: |
          echo "PACKAGE_VERSION=$(jq -r .version package.json)"
          echo "PACKAGE_VERSION=$(jq -r .version package.json)" >>${GITHUB_ENV}
      - name: docker login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: build and publish image
        run: |
          docker build . \
            --tag ghcr.io/${{ env.IMAGE_NAME }}:latest \
            --tag ghcr.io/${{ env.IMAGE_NAME }}:${{ env.PACKAGE_VERSION }} \
            --tag ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ghcr.io/${{ env.IMAGE_NAME }} --all-tags
